title = "Almighwar"
baseURL = '/'

# <html lang="">
languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To Google Analytics 4 (gtag.js)
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  # [[menu.main]]
    # pageRef="/"
    # name = 'Home'
    # url = '/'
    # weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="stories"
    name = 'Stories'
    url = '/stories/'
    weight = 30
  [[menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 40

[params]
  sitename = "Almighwar"
  defaultColor = "auto"  # set color mode: dark, light, auto
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Blog that i written in it, all my notes"
  mainSections = ['posts']
  toc = true # set 'false' to disable table of contents
  goToTop = true # set 'false' to disable 'go to top' button
  summary_length = 100 # number of characteres of Summary below the posts

[params.author]
  # avatar goes to 'partial/bio.html' lines 5 and 8
  intro = "Enjoy it, Interested things"
  description = "In the end the purpose behind it matter than form, To share with people my intrested things."

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/almighwar"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/almighwar_"

[tableOfContents]
startLevel = 1
endLevel = 4 
ordered = false # generates <ul> instead of <ol>

